[package]
name = "content_scan"
version = "0.1.7"
edition = "2021"
authors = ["Gavrilut Dragos <gavrilut.dragos@gmail.com>"]
license = "MIT"
description = "An extensible, plugin-based framework for identifying, analyzing, and recursively extracting structured content from arbitrary bytes."
repository = "https://github.com/gdt050579/content_scan"
homepage = "https://github.com/gdt050579/content_scan"
documentation = "https://docs.rs/content_scan"
readme = "../README.md"
keywords = ["scanner", "content", "extraction", "file-format", "plugin"]
categories = ["data-structures", "algorithms", "filesystem"]


[lib]

[dependencies]
varmap = "0.1.3"
filecache = { version = "0.1.1", features = ["mmap"] }
zip = "8.6.0"
content_scan_proc_macro = "0.1.3"
# content_scan_proc_macro = { path = "../content-scan-proc-macro" }