[package]
name = "content_scan_proc_macro"
version = "0.1.1"
edition = "2021"
authors = ["Gavrilut Dragos <gavrilut.dragos@gmail.com>"]
description = "Procedural macros for the content_scan_proc_macro library."
license = "MIT"
repository = "https://github.com/gdt050579/content_scan"
readme = "../README.md"
keywords = ["varmap", "proc-macro"]
categories = ["development-tools::procedural-macro-helpers"]
documentation = "https://docs.rs/content-scan-proc-macro"

[lib]
proc-macro = true

[dependencies]

[lints]
workspace = true