[package]
name = "examples"
version = "0.0.0"
publish = false
edition = "2021"

[dev-dependencies]
content_scan = { path = "../content_scan" }
md-5 = "0.10"


[[example]]
name = "vowals"
path = "vowals/main.rs"

[[example]]
name = "sum"
path = "sum/main.rs"

[[example]]
name = "image_size"
path = "image_size/main.rs"

[[example]]
name = "base64_find"
path = "base64_find/main.rs"

[[example]]
name = "md5"
path = "md5/main.rs"

[[example]]
name = "entropy"
path = "entropy/main.rs"

[[example]]
name = "find_zip"
path = "find_zip/main.rs"

[[example]]
name = "zip_png_size"
path = "zip_png_size/main.rs"
