[package]
name = "examples"
version = "0.0.0"
publish = false
edition = "2021"

[dev-dependencies]
content_scan = { path = "../content_scan" }
varmap = "*"


[[example]]
name = "vowals"
path = "vowals/main.rs"

[[example]]
name = "sum"
path = "sum/main.rs"

[[example]]
name = "image_size"
path = "image_size/main.rs"
